apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeus
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hecate
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerberus
spec:
  replicas: 1
