apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unkaos-dev

resources:
  - ../../base

patchesStrategicMerge:
  - patches/replicas.yaml
  - patches/resources.yaml

configMapGenerator:
  - name: unkaos-config
    behavior: merge
    literals:
      - DOMAIN=dev.unkaos.local
      - DB_HOST=postgres-service.unkaos-dev.svc.cluster.local
