apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unkaos-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: unkaos.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hecate-service
            port:
              number: 3001
      - path: /api/zeus
        pathType: Prefix
        backend:
          service:
            name: zeus-service
            port:
              number: 3006
      - path: /api/cerberus
        pathType: Prefix
        backend:
          service:
            name: cerberus-service
            port:
              number: 3005
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: hermes-service
            port:
              number: 5009
